
GET http://localhost:8080/expenses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJuYW1lIjoiVGVzdCIsImV4cCI6MTc5MDg2NzczNiwiaXNzIjoiRXhwZW5zZVRyYWNrZXJBcGkiLCJhdWQiOiJFeHBlbnNlVHJhY2tlckNsaWVudCJ9.cKKLltOl-8MBQksgbvRqf6kRHhvhNZgtwFAuhnrwc9Q

###

//GET /expenses/1
GET http://localhost:5127/expenses/1
Authorization: Bearer 

{
    "name": "Fish Market Groceries",
    "categoryId": 3,
    "amount": 400,
    "paymentDate": "2026-06-03"
}

###
// PUT /expenses/1
PUT http://localhost:5127/expenses/1
Authorization: Bearer 
Content-Type: application/json

{
    "name": "Chester Groceries",
    "categoryId": 3,
    "amount": 900,
    "paymentDate": "2026-06-03"
}

###

//DELETE /expenses/1
DELETE http://localhost:5127/expenses/3

###
//GET /categories
GET http://localhost:5127/categories

###
//POST /auth/register
POST http://localhost:5127/auth/register
Content-Type: application/json

{
    "name": "",
    "email": "",
    "password": ""
}

###
//POST /auth/login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "12345678"
}